version: "3.9"

services:
  db:
    image: postgres:15
    container_name: octagoniq_db
    restart: always
    environment:
      POSTGRES_USER: octagon
      POSTGRES_PASSWORD: octagonpass
      POSTGRES_DB: octagoniq
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: octagoniq_backend
    restart: always
    depends_on:
      - db
      - test_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://octagon:octagonpass@db:5432/octagoniq
      TEST_DATABASE_URL: postgresql://postgres:postgres@test_db:5432/test_db
      SECRET_KEY: supersecretkey123
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      ALGORITHM: HS256
      PYTHONPATH: /app

volumes:
  postgres_data: